### ISSUE TITLE
Adding "has_message_been_ticked" to ConditionTopicSubscriber

### ISSUE THREAD

**Issue by MrBlenny** [miccol/ros2_bt_utils#2]
Ciao,
I'm new to BTs so I'm still not quite sure where your project fits in the ecosystem...

For my use-case, I want a condition that only succeeds the first time the node is ticked for each message (I have a ROS topic that receives a message each time a button is pressed - I only want to process that event once). This is sort of like `first_time` as seen [here](https://github.com/ros-planning/navigation2/blob/main/nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/path_expiring_timer_condition.hpp#L68) but `has_message_been_ticked` would be set to `false` when the subscriber receives a message and `true` once it has been ticked. Maybe it would make sense to pass this into the [elaborateMessageAndReturn function](https://github.com/miccol/ros2_bt_utils/blob/main/include/ros2_bt_utils/condition_topic_subscriber.hpp#L88) 

Do you feel this is a reasonable use-case that makes sense to belong here?

On a related note, how would this work with something like a [switch_node](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/include/behaviortree_cpp_v3/controls/switch_node.h)

Cheerio

**Comment by miccol** [comment]
Ciao!
just to check if I got your use case: if the condition node reads the same message, you want the condition to return SUCCESS the first time and then FAILURE; the condition node would return success again only if the message received changes, correct?

About the switch node, it is not currently available but I don't see any problem in implementing it and put the condition above as a child

**Comment by MrBlenny** [comment]
Great thanks,
I'm just having a bit of a play today with some other actions nodes for example a `ActionTopicPublisher` that publishes to ROS when it is ticked. Will create a PR here if you think something like that should belong in `ros2_bt_utils`

**Comment by miccol** [comment]
cool! thanks!
